name: React Events

on:
  pull_request:
    types:
      - opened
    branches:
      - main
    paths:
      - 'react-events/**'
      - '.github/workflows/react-events.yml'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./react-events

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"

      - name: Get code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Run build
        run: npm run build

      - name: Deploy project
        run: echo "Deploying..."
